#!/usr/bin/env python

"""
setup.py file for SWIG example
"""

from distutils.core import setup, Extension


rok4IO_module = Extension('_rok4io',
                            include_dirs=['../libjpeg', '../libpng'],
                            libraries=['z'],
                           sources=['rok4IO_wrap.cxx', 'ImageIO.cpp',
                            '../libjpeg/cdjpeg.c',
                            # '../libjpeg/cjpeg.c',
                            # '../libjpeg/ckconfig.c',
                            # '../libjpeg/djpeg.c',
                            # '../libjpeg/example.c',
                            '../libjpeg/jaricom.c',
                            '../libjpeg/jcapimin.c',
                            '../libjpeg/jcapistd.c',
                            '../libjpeg/jcarith.c',
                            '../libjpeg/jccoefct.c',
                            '../libjpeg/jccolor.c',
                            '../libjpeg/jcdctmgr.c',
                            '../libjpeg/jchuff.c',
                            '../libjpeg/jcinit.c',
                            '../libjpeg/jcmainct.c',
                            '../libjpeg/jcmarker.c',
                            '../libjpeg/jcmaster.c',
                            '../libjpeg/jcomapi.c',
                            '../libjpeg/jcparam.c',
                            '../libjpeg/jcprepct.c',
                            '../libjpeg/jcsample.c',
                            '../libjpeg/jctrans.c',
                            '../libjpeg/jdapimin.c',
                            '../libjpeg/jdapistd.c',
                            '../libjpeg/jdarith.c',
                            '../libjpeg/jdatadst.c',
                            '../libjpeg/jdatasrc.c',
                            '../libjpeg/jdcoefct.c',
                            '../libjpeg/jdcolor.c',
                            '../libjpeg/jddctmgr.c',
                            '../libjpeg/jdhuff.c',
                            '../libjpeg/jdinput.c',
                            '../libjpeg/jdmainct.c',
                            '../libjpeg/jdmarker.c',
                            '../libjpeg/jdmaster.c',
                            '../libjpeg/jdmerge.c',
                            '../libjpeg/jdpostct.c',
                            '../libjpeg/jdsample.c',
                            '../libjpeg/jdtrans.c',
                            '../libjpeg/jerror.c',
                            '../libjpeg/jfdctflt.c',
                            '../libjpeg/jfdctfst.c',
                            '../libjpeg/jfdctint.c',
                            '../libjpeg/jidctflt.c',
                            '../libjpeg/jidctfst.c',
                            '../libjpeg/jidctint.c',
                            # '../libjpeg/jmemansi.c',
                            # '../libjpeg/jmemdos.c',
                            # '../libjpeg/jmemmac.c',
                            '../libjpeg/jmemmgr.c',
                            # '../libjpeg/jmemname.c',
                            '../libjpeg/jmemnobs.c',
                            # '../libjpeg/jpegtran.c',
                            '../libjpeg/jquant1.c',
                            '../libjpeg/jquant2.c',
                            '../libjpeg/jutils.c',
                            '../libjpeg/rdbmp.c',
                            '../libjpeg/rdcolmap.c',
                            '../libjpeg/rdgif.c',
                            # '../libjpeg/rdjpgcom.c',
                            '../libjpeg/rdppm.c',
                            '../libjpeg/rdrle.c',
                            '../libjpeg/rdswitch.c',
                            '../libjpeg/rdtarga.c',
                            '../libjpeg/transupp.c',
                            '../libjpeg/wrbmp.c',
                            '../libjpeg/wrgif.c',
                            '../libjpeg/wrjpgcom.c',
                            '../libjpeg/wrppm.c',
                            '../libjpeg/wrrle.c',
                            '../libjpeg/wrtarga.c',
                            # '../libpng/example.c',
                            '../libpng/png.c',
                            '../libpng/pngerror.c',
                            '../libpng/pngget.c',
                            # '../libpng/pnglibconf.c',
                            '../libpng/pngmem.c',
                            '../libpng/pngpread.c',
                            '../libpng/pngread.c',
                            '../libpng/pngrio.c',
                            '../libpng/pngrtran.c',
                            '../libpng/pngrutil.c',
                            '../libpng/pngset.c',
                            # '../libpng/pngtest.c',
                            '../libpng/pngtrans.c',
                            '../libpng/pngwio.c',
                            '../libpng/pngwrite.c',
                            '../libpng/pngwtran.c',
                            '../libpng/pngwutil.c']
                           )

setup (name = 'rok4io',
       version = '0.1',
       author      = "Ign",
       description = """ROK4IO""",
       ext_modules = [rok4IO_module],
       py_modules = ["rok4io"],
       )